/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AdminController;
import Controller.LoginController;

/**
 *
 * @author ASUS
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stdlabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        ForgetpassLable = new javax.swing.JLabel();
        createAccLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        passwordPF = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stdlabel.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        stdlabel.setText("Student Login");
        stdlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stdlabelMouseClicked(evt);
            }
        });
        jPanel1.add(stdlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 100, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 0));
        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel3.setText("User Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 130, 90, 25);

        jLabel5.setBackground(new java.awt.Color(255, 255, 0));
        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel5.setText("Password:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(80, 180, 90, 25);
        jPanel2.add(nameTF);
        nameTF.setBounds(190, 130, 250, 25);

        ForgetpassLable.setBackground(new java.awt.Color(255, 255, 0));
        ForgetpassLable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ForgetpassLable.setText("Forget Password?");
        ForgetpassLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgetpassLableMouseClicked(evt);
            }
        });
        jPanel2.add(ForgetpassLable);
        ForgetpassLable.setBounds(330, 210, 101, 15);

        createAccLabel.setBackground(new java.awt.Color(255, 255, 0));
        createAccLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        createAccLabel.setText("Create new User Account");
        createAccLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccLabelMouseClicked(evt);
            }
        });
        jPanel2.add(createAccLabel);
        createAccLabel.setBounds(190, 240, 160, 17);

        loginBtn.setBackground(new java.awt.Color(255, 255, 102));
        loginBtn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginBtn);
        loginBtn.setBounds(190, 280, 91, 37);

        cancelBtn.setBackground(new java.awt.Color(255, 255, 102));
        cancelBtn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel2.add(cancelBtn);
        cancelBtn.setBounds(330, 280, 107, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-locked-64.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(260, 0, 80, 70);

        passwordPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordPFMouseClicked(evt);
            }
        });
        passwordPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPFActionPerformed(evt);
            }
        });
        jPanel2.add(passwordPF);
        passwordPF.setBounds(190, 180, 250, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setText("Admin Only");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 50, 230, 70);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 610, 380));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-100.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 90, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 780, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPFActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        AdminController.Login(nameTF.getText(),passwordPF.getText());
    }//GEN-LAST:event_loginBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
      super.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void createAccLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccLabelMouseClicked
        // TODO add your handling code here:
        AdmincreateForm label = new AdmincreateForm();
        label.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_createAccLabelMouseClicked

    private void ForgetpassLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetpassLableMouseClicked
        // TODO add your handling code here:
        AdminForget pass = new AdminForget();
        pass.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_ForgetpassLableMouseClicked

    private void passwordPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordPFMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPFMouseClicked

    private void stdlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdlabelMouseClicked
        // TODO add your handling code here:
       StudentLogin back =new StudentLogin();
       back.setVisible(true);
       super.dispose();
    }//GEN-LAST:event_stdlabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ForgetpassLable;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel createAccLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JLabel stdlabel;
    // End of variables declaration//GEN-END:variables
}
