/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.InsertController;
import Model.DBSearch;

/**
 *
 * @author ASUS
 */
public class StudentRegForm extends javax.swing.JFrame {

    /**
     * Creates new form register1
     */
    public StudentRegForm() {
        initComponents();
    }
    
    public void Clearfield(){
        TFname.setText("");
        TFContact.setText("");
        TFAddress.setText("");
        TFNIC.setText("");
        dobTF.setText("");
        
        programCMB4.setSelectedIndex(0);
        diuComboBox.setSelectedIndex(0);
        TFemail.setText("");
        RFullBtn.setSelected(false);
        RPartBtn.setSelected(false);
        RBtnMale.setSelected(false);
        RBtnFemale.setSelected(false);
        Paid1.setSelected(false);
        NotPaid.setSelected(false);
    }
  //  public void Clearfield1(){
        
       
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        TFname = new javax.swing.JTextField();
        TFContact = new javax.swing.JTextField();
        TFAddress = new javax.swing.JTextField();
        TFNIC = new javax.swing.JTextField();
        RBtnMale = new javax.swing.JRadioButton();
        RBtnFemale = new javax.swing.JRadioButton();
        TFemail = new javax.swing.JTextField();
        programCMB4 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        RFullBtn = new javax.swing.JRadioButton();
        RPartBtn = new javax.swing.JRadioButton();
        BtnClear = new javax.swing.JButton();
        SubmitBtn = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        diuComboBox = new javax.swing.JComboBox<>();
        dobTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NotPaid = new javax.swing.JRadioButton();
        Paid1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 800));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel42.setText("Full Name");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 188, -1, -1));

        jLabel43.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel43.setText("Contact No:");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 228, -1, -1));

        jLabel44.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel44.setText("Address:");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel45.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel45.setText("Date of Birth");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 133, -1));

        jLabel50.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel50.setText("NIC:");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel46.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel46.setText("Gender:");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel47.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel47.setText("Degree Programme:");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 19));

        jLabel49.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel49.setText("E-mail:");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, 20));

        jLabel41.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 0, 102));
        jLabel41.setText("Register New Student");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 119, 462, -1));
        jPanel1.add(TFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 188, 339, -1));

        TFContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFContactActionPerformed(evt);
            }
        });
        jPanel1.add(TFContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 228, 339, -1));

        TFAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAddressActionPerformed(evt);
            }
        });
        jPanel1.add(TFAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 339, -1));
        jPanel1.add(TFNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 339, -1));

        buttonGroup1.add(RBtnMale);
        RBtnMale.setText("Male");
        RBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnMaleActionPerformed(evt);
            }
        });
        jPanel1.add(RBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        buttonGroup1.add(RBtnFemale);
        RBtnFemale.setText("Female");
        RBtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(RBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));
        jPanel1.add(TFemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 339, 25));

        programCMB4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSc (Hons) in Information Technology", "BIT (Hons) Networking and Mobile Computing", "BSc in Businessf Management (HRM)", "BM (Hons) in Marketing", "BSc (Hons) Biotechnology ", "BSc (Hons) in Physical Science", "BSc (Hons) in Biological Science" }));
        programCMB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programCMB4programCMBActionPerformed(evt);
            }
        });
        jPanel1.add(programCMB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 339, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Degree Type");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        buttonGroup5.add(RFullBtn);
        RFullBtn.setText("Full Time");
        RFullBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFullBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RFullBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, -1, -1));

        buttonGroup5.add(RPartBtn);
        RPartBtn.setText("Part Time");
        jPanel1.add(RPartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, -1));

        BtnClear.setBackground(new java.awt.Color(255, 255, 51));
        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        jPanel1.add(BtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 80, 30));

        SubmitBtn.setBackground(new java.awt.Color(255, 255, 51));
        SubmitBtn.setText("Submit");
        SubmitBtn.setPreferredSize(new java.awt.Dimension(60, 25));
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 660, 80, 30));

        BtnBack.setBackground(new java.awt.Color(255, 255, 51));
        BtnBack.setText("Log Out");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 80, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Diuration of the degree");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        diuComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 Years", "4 Years", "5 Years" }));
        jPanel1.add(diuComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 339, -1));

        dobTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTFActionPerformed(evt);
            }
        });
        jPanel1.add(dobTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 339, -1));

        jLabel2.setText("Rs.50,000.00");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 117, 25));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Register Fee");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 105, 25));

        buttonGroup6.add(NotPaid);
        NotPaid.setText("Not paid");
        NotPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotPaidActionPerformed(evt);
            }
        });
        jPanel1.add(NotPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, -1, -1));

        buttonGroup6.add(Paid1);
        Paid1.setText("Paid");
        jPanel1.add(Paid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));
        jPanel4.setForeground(new java.awt.Color(0, 51, 153));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo4.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("A Home for your Higher ");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Education");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)))
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel12.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 750, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 750);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TFContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFContactActionPerformed

    private void TFAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAddressActionPerformed

    private void programCMB4programCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programCMB4programCMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programCMB4programCMBActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
            StudentLogin stdnew = new StudentLogin();
            stdnew.setVisible(true);
            super.dispose();
       
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        // TODO add your handling code here:
        Clearfield();
        //Clearfield1();
        
    }//GEN-LAST:event_BtnClearActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        String gender = null;
        
        if(RBtnMale.isSelected()){
            gender = "Male";
        }
        else if(RBtnFemale.isSelected()){
            gender = "Female";
        }
        
        String degreeType = null;
        
        if(RFullBtn.isSelected()){
            degreeType = "Full Time";
        }
        else if(RBtnFemale.isSelected()){
            degreeType = "Part Time";
        }
        String pay = null;
        
        if(Paid1.isSelected()){
            pay = "Paid";
        }
        else if(NotPaid.isSelected()){
            pay = "NotPaid";
        }
       
        String programm = programCMB4.getSelectedItem().toString();
        String diu = diuComboBox.getSelectedItem().toString();
        //String date = DCdate.getDate().toString();
        
        InsertController.RegStu(TFname.getText(),TFContact.getText(),TFAddress.getText(),dobTF.getText(),TFNIC.getText(), gender, programm, diu, degreeType, TFemail.getText(), pay);
        
        /*DBSearch var = new DBSearch();
        var.nic = 
        `/*TFNIC.getText();/*/
       // PaymentDetails next = new PaymentDetails();
       // next.setVisible(true);
      // PaymentDetails p = new PaymentDetails();
       //p.setVisible(true);
       super.dispose();
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void RBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBtnMaleActionPerformed

    private void RBtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBtnFemaleActionPerformed

    private void RFullBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFullBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RFullBtnActionPerformed

    private void dobTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTFActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_dobTFActionPerformed

    private void NotPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotPaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotPaidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentRegForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnClear;
    private javax.swing.JRadioButton NotPaid;
    private javax.swing.JRadioButton Paid1;
    private javax.swing.JRadioButton RBtnFemale;
    private javax.swing.JRadioButton RBtnMale;
    private javax.swing.JRadioButton RFullBtn;
    private javax.swing.JRadioButton RPartBtn;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JTextField TFAddress;
    private javax.swing.JTextField TFContact;
    public javax.swing.JTextField TFNIC;
    private javax.swing.JTextField TFemail;
    private javax.swing.JTextField TFname;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JComboBox<String> diuComboBox;
    private javax.swing.JTextField dobTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JComboBox<String> programCMB4;
    // End of variables declaration//GEN-END:variables

    private AdminHome Home() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
